# Generated by Django 4.1.2 on 2023-01-15 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_rep_acc', '0002_booking_club_films'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='club_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_rep_acc.clubrep'),
        ),
        migrations.AddField(
            model_name='booking',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_rep_acc.films'),
        ),
        migrations.AddField(
            model_name='club',
            name='club_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_rep_acc.clubrep'),
        ),
    ]
